name: Publish Nuget Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the package'
        required: true
        default: '0.0.0'

jobs:
  build:
    name: Build .NET and Publish Nuget Package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Pack
        run: dotnet pack Fusionary.BigCommerceApi/Fusionary.BigCommerceApi/Fusionary.BigCommerce.csproj --configuration Release
      - name: Tag
        uses: EndBug/latest-tag@latest
        with:
          ref: v${{ github.event.inputs.version }}
      - name: Publish
        run: dotnet nuget push "**/*.nupkg" --skip-duplicate
